<?xml version="1.0"?>
<package format="3">
  <name>wla_diff_mpc</name>
  <version>0.1.0</version>
  <description>OSQP differential-drive MPC Nav2 controller.</description>
  <maintainer email="1330367040@qq.com">jakukur</maintainer>
  <license>Apache-2.0</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>geometry_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>nav2_core</depend>
  <depend>nav2_costmap_2d</depend>
  <depend>nav2_util</depend>
  <depend>pluginlib</depend>
  <depend>rclcpp</depend>
  <depend>rclcpp_lifecycle</depend>
  <depend>tf2</depend>
  <depend>tf2_geometry_msgs</depend>
  <depend>tf2_ros</depend>
  <depend>eigen3_cmake_module</depend>
  <depend>osqp-eigen</depend>
  <export><build_type>ament_cmake</build_type></export>
</package>
